### ISSUE TITLE
Priority Speed

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/daemon-disqualifier#26]
Divide the config timeouts by the priority level. This makes follow ups more aggressive based on the priority level. 

`Priority: 5 (Emergency)` Means divide by 5. 

- warning = 3.5 days / 5 = 16.8 hours
-  disqualify = 7 days / 5 = 33.6 hours

Should be configurable (priority enabled: Boolean)

**Comment by 0x4007** [comment]
Maybe we should make a config manifest (so a file with a different name in each plugin) that describes every configurable property and provides a description, their default values, and example of every config property in every plugin? Then we can read this for our plugin configuration GUI.

**Comment by Keyrxng** [comment]
> Perhaps this was already discussed as it vaguely rings a bell.

I mentioned something very similar on TG and I think it would be better if the standard `manifest.json` contained this info. It could allow external settings validation as opposed to it being bound to inside the plugin because we could take it directly from the manifest.

I think if we are updating the `manifest.json` we should also convert the events into keys so we can dynamically type `SupportedEvents`

**Comment by ishowvel** [comment]
So the specification for this issue is to
make a property in the manifest json to enable aggressive followups based on the priority level and disqualify based on those new aggresive deadlines?

**Comment by 0x4007** [comment]
Everything has to do with .ubiquity-os.config.yml actually. Don't worry about the manifest.

**Comment by gentlementlegen** [comment]
It is possible to add more data in the schema such as value restriction, patterns, or descriptions that would end up automatically in the manifest afterwards.
